// import 'package:flutter/material.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           AndroidLarge2(),
//         ]),
//       ),
//     );
//   }
// }

// class AndroidLarge2 extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 360,
//           height: 800,
//           clipBehavior: Clip.antiAlias,
//           decoration: ShapeDecoration(
//             color: Colors.white,
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(20),
//             ),
//           ),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 35,
//                 top: 44,
//                 child: Container(
//                   width: 291,
//                   height: 207,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage(
//                           "https://i.pinimg.com/originals/62/dd/c4/62ddc455488a13d67f4198a09dc4bb29.gifs"),
//                       fit: BoxFit.contain,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 106,
//                 top: 111,
//                 child: Container(
//                   width: 175,
//                   height: 266,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage(
//                           "https://i.pinimg.com/originals/62/dd/c4/62ddc455488a13d67f4198a09dc4bb29.gif"),
//                       fit: BoxFit.contain,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 87,
//                 top: 482,
//                 child: Text(
//                   'Parcel delivery',
//                   style: TextStyle(
//                     color: Colors.black.withOpacity(0.75),
//                     fontSize: 24,
//                     fontFamily: 'Montserrat',
//                     fontWeight: FontWeight.w700,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 163,
//                 top: 458,
//                 child: Container(
//                   width: 34,
//                   child: Stack(
//                     children: [
//                       Positioned(
//                         left: 0,
//                         top: 1,
//                         child: Container(
//                           width: 8,
//                           height: 8,
//                           decoration: ShapeDecoration(
//                             color: Color(0x7F1E1E1E),
//                             shape: OvalBorder(),
//                           ),
//                         ),
//                       ),
//                       Positioned(
//                         left: 12,
//                         top: 0,
//                         child: Container(
//                           width: 10,
//                           height: 10,
//                           decoration: ShapeDecoration(
//                             color: Colors.black,
//                             shape: OvalBorder(),
//                           ),
//                         ),
//                       ),
//                       Positioned(
//                         left: 26,
//                         top: 1,
//                         child: Container(
//                           width: 8,
//                           height: 8,
//                           decoration: ShapeDecoration(
//                             color: Color(0x7F1E1E1E),
//                             shape: OvalBorder(),
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 33,
//                 top: 526,
//                 child: SizedBox(
//                   width: 293,
//                   child: Text(
//                     'Ship & track parcels and packages and learn about our express courier services!',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Colors.black.withOpacity(0.6499999761581421),
//                       fontSize: 16,
//                       fontFamily: 'Inter',
//                       fontWeight: FontWeight.w500,
//                       height: 0,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 65,
//                 top: 634,
//                 child: Container(
//                   width: 229,
//                   height: 40,
//                   decoration: ShapeDecoration(
//                     color: Colors.black,
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(30),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 110,
//                 top: 644,
//                 child: Text(
//                   'Create an account',
//                   textAlign: TextAlign.center,
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 16,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w500,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 69,
//                 top: 698,
//                 child: Text.rich(
//                   TextSpan(
//                     children: [
//                       TextSpan(
//                         text: 'Already have an account? ',
//                         style: TextStyle(
//                           color: Colors.black.withOpacity(0.8100000023841858),
//                           fontSize: 14,
//                           fontFamily: 'Inter',
//                           fontWeight: FontWeight.w500,
//                           height: 0,
//                         ),
//                       ),
//                       TextSpan(
//                         text: 'Sign in',
//                         style: TextStyle(
//                           color: Color(0xFFFECE00),
//                           fontSize: 14,
//                           fontFamily: 'Inter',
//                           fontWeight: FontWeight.w700,
//                           decoration: TextDecoration.underline,
//                           height: 0,
//                         ),
//                       ),
//                     ],
//                   ),
//                   textAlign: TextAlign.center,
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }
